CAVEconnectome/CAVEclient

annotationframeworkclient/chunkedgraph.py, annotationframeworkclient/endpoints.py
Opening a PR for adding level 2 features to the chunkedgraph client. Docs not yet updated, but would like a quick discussion of the code updates.
=> Add level2 chunk features

annotationframeworkclient/base.py, annotationframeworkclient/endpoints.py, annotationframeworkclient/frameworkclient.py, annotationframeworkclient/infoservice.py, annotationframeworkclient/materializationengine.py, requirements.txt
Here is the materialization client PR.. please take a scan!
=> Materialization client

annotationframeworkclient/chunkedgraph.py, annotationframeworkclient/endpoints.py
Is there any reason not to merge this into master? If we don't want to expose this endpoint to anyone for PCG performance reasons, it should be under a more restricted permissions, not obscured at the client level.
=> Add subgraph

annotationframeworkclient/annotationengine.py, annotationframeworkclient/base.py, annotationframeworkclient/infoservice.py, annotationframeworkclient/materializationengine.py
added the verify option to the base class to help with localhost testing of unverified https servers
=> Add verify

annotationframeworkclient/materializationengine.py
this enables the new options that I implemented here https://github.com/seung-lab/MaterializationEngine/pull/17
=> adding support for compressed json and dataframes

annotationframeworkclient/chunkedgraph.py, annotationframeworkclient/endpoints.py
Adding functions for the new lineage graph features
=> Lineage graph endpoint

annotationframeworkclient/materializationengine.py
fixes column recombining to be backward compatible
=> fixing column recombining

annotationframeworkclient/annotationengine.py
Still working on testing this, but wanted more feedback
=> adding post and update with dataframe

annotationframeworkclient/chunkedgraph.py, annotationframeworkclient/endpoints.py, annotationframeworkclient/frameworkclient.py, annotationframeworkclient/materializationengine.py, requirements.txt
adds live query functionality to python client
=> Live query

annotationframeworkclient/annotationengine.py, annotationframeworkclient/base.py, annotationframeworkclient/chunkedgraph.py, annotationframeworkclient/materializationengine.py
I needed to set the verify state on the session, and now we can remove all the verify calls in the individual methods.
=> fixing verify for localhost testing

annotationframeworkclient/annotationengine.py, annotationframeworkclient/auth.py, annotationframeworkclient/base.py, annotationframeworkclient/chunkedgraph.py, annotationframeworkclient/emannotationschemas.py, annotationframeworkclient/format_utils.py, annotationframeworkclient/frameworkclient.py, annotationframeworkclient/infoservice.py, annotationframeworkclient/jsonservice.py, annotationframeworkclient/materializationengine.py, annotationframeworkclient/timeit.py, setup.py, tests/conftest.py, tests/test_chunkedgraph.py, tests/test_materialization.py
just ran black on all the python files
=> Black reformat

annotationframeworkclient/auth.py
making it easier to swap between servers and tokens
=> looks for a server specific cloudvolume token

annotationframeworkclient/annotationengine.py, annotationframeworkclient/base.py
adding voxel resolution to framework client
=> adding voxel resolution

caveclient/chunkedgraph.py, caveclient/endpoints.py, tests/test_chunkedgraph.py
adds this endpoint to chunkedgraph client with tests
=> Cg delta roots

caveclient/frameworkclient.py, caveclient/materializationengine.py
adds a synapse query function and give query_table a timestamp option (to enable passthrough to live query)
=> Synapse query

.bumpversion.cfg, caveclient/__init__.py, caveclient/materializationengine.py, docs/guide/materialization.rst
This adds support for spatial filtering, and improves the way the materialization client returns voxel resolutions.
=> spatial filtering and voxel resolution array 

CAVEclientExamples.ipynb, caveclient/auth.py, caveclient/base.py, caveclient/endpoints.py, caveclient/infoservice.py, docs/guide/authentication.rst, docs/guide/framework.rst
This improves the way the caveclient reacts to not signing of the TOS, as well as updates and improves documentation of initial process of setting up client.
=> Tos improvements

caveclient/chunkedgraph.py, tests/test_chunkedgraph.py
=> Better datatype checking in chunkedgraph module

caveclient/chunkedgraph.py, caveclient/endpoints.py, tests/test_chunkedgraph.py
Access the multicut preview endpoint via the client.
=> Preview split

caveclient/frameworkclient.py, caveclient/infoservice.py, caveclient/materializationengine.py, tests/conftest.py, tests/test_infoservice.py, tests/test_materialization.py
Adding a feature to be able to specify desired resolution of position columns. 
Could not implement trivially for join due to possibility of different resolution for different tables and no good way of tracking columns.. need to await for schema awareness to integrate into client.
=> Desired resolution

caveclient/auth.py, caveclient/chunkedgraph.py, caveclient/endpoints.py
Currently only for pcgv1. pcgv2 has an untested PR pending: https://github.com/seung-lab/PyChunkedGraph/pull/393. Need to wait for that to be deployed before merging this PR.
=> Added valid node request to chunkedgraph

caveclient/auth.py, caveclient/endpoints.py
Add auth.get_group_users function to get list of users in a group
=> Get_groups

.bumpversion.cfg, caveclient/__init__.py, caveclient/chunkedgraph.py, caveclient/endpoints.py, caveclient/infoservice.py, caveclient/materializationengine.py
adding split and ingest annotations
=> split and ingestion

caveclient/chunkedgraph.py, caveclient/endpoints.py
adding an get oldest timestamp call
=> Add oldest timestamp

caveclient/l2cache.py
I think we've moved past this stage now
=> remove warning about L2 cache

caveclient/datastack_lookup.py
Gracefully handle unwritable files
=> Datastack to server map

caveclient/base.py, caveclient/jsonservice.py, caveclient/materializationengine.py, tests/test_materialization.py
Starting a PR for client side handling of the IPC pyarrow serialization format to go along with server changes.
Still needs more testing before merge and release.
=> Client side serialization

caveclient/format_utils.py, caveclient/materializationengine.py
add new pyarrow formatting argument across all queries
=> Query arg bug

caveclient/materializationengine.py, docs/guide/materialization.rst
=> Fix typo in MaterializationClientV2/V3

caveclient/chunkedgraph.py, tests/test_chunkedgraph.py
Companion to https://github.com/seung-lab/PyChunkedGraph/pull/488
=> Add bounding box argument to `level2_chunk_graph`

caveclient/base.py, caveclient/materializationengine.py
Closes #190 and also documents other properties while I was here. 
Mostly just makes it so that these will show up in the generated docs site.
=> Document properties in materialization

caveclient/jsonservice.py
Fix the endpoint mapping for the `get_property_json` call
=> fix get_property_json endpoint lookup

caveclient/tools/table_manager.py
In the case where there was a column name collision between a table and its reference table, the `materialize.tables` interface was not building queries with the correct column name even though it was smart enough to keep that information in its metadata. This PR fixes this.
=> correct field names when columns collide

caveclient/skeletonservice.py
Closes https://github.com/CAVEconnectome/CAVEclient/issues/231
=> Remove global warning for skeleton service w/o Cloudvolume

caveclient/endpoints.py, caveclient/skeletonservice.py, caveclient/tools/testing.py, docs/tutorials/skeletonization.md, tests/test_skeletons.py
I created initial skeletonservice tests a few weeks ago on a side branch but never merged them into master. Given the divergence of (and from) master in the intervening time, I started over with a new branch built off master and got the tests running again — painfully. I would like to merge them in quickly before another wave of master/dev-branch divergence sweeps in and breaks everything all over again. Thanks for your timely follow-up on this.
=> Skeletonservice tests2

caveclient/skeletonservice.py
Removes casting for swc returns on the client side
See related https://github.com/navis-org/navis/issues/183
=> Remove type casting in skeleton SWCs

caveclient/materializationengine.py
=> Remove unused kwarg in `query_view`

caveclient/annotationengine.py
I punted on JSON responses bc those seem like they can be anything, but if someone wants to improve, feel free
=> Add some typing to annotation client
