annotationframeworkclient/chunkedgraph.py
annotationframeworkclient/materializationengine.py

Added a few features:
1. An argument to `get_roots` that goes through a different endpoint to look up root ids up to a given stop level.
2. A client.materialize.get_timestamp() function that generates a datetime object that can be passed directly to the chunkedgraph client calls.
3. A client.materialize.version property setter that checks to ensure the specified version is in a version from get_versions.

Improved level2 lookup

---

annotationframeworkclient/annotationengine.py
annotationframeworkclient/chunkedgraph.py
annotationframeworkclient/frameworkclient.py
annotationframeworkclient/materializationengine.py
docs/api/annotationframeworkclient.rst
docs/guide/annotation.rst
docs/guide/chunkedgraph.rst
docs/guide/materialization.rst
docs/index.rst
requirements.txt

I did some updating of the documentation to include the materialization.  In the process I realized there were some features and changes that should make things easier and faster for the client. 
I added a 'homepage' property to materialization in order to let people browse things that way.
I moved the recombination of columns to the client side, because there were major speed improvements in serialization and deserialization when passing uniform numpy arrays over the wire.
I made all the metadata objects return datetime converting objects, rather than leaving that to the user. 
I also put in some example hyperlinks throughout the docs that bring the user to the function/class docstrings directly.   We should use these more broadly.

Doc updates

---

annotationframeworkclient/endpoints.py
annotationframeworkclient/materializationengine.py

Two fixes for the client that I needed to make it work with my existing workflows.
1) Update the default global endpoint to `global.daf-apis.com` (no v1)
2) Allow explicit `datetime.datetime` objects for materialization, not just the specific string format that the PyChunkedGraph uses.

Endpoint + materialization timestamp

---

caveclient/endpoints.py
caveclient/frameworkclient.py
caveclient/l2cache.py

Examples:
```
import numpy as np
import datetime
from caveclient import CAVEclient
datastack_name = "flywire_fafb_production"
client = CAVEclient(datastack_name)
l2_ids = [175137943013294113, 175137943013294114, 175137943013294118, 175137943013294119,]
```
```
client.l2cache.get_l2data(l2_ids)
```
```
{'175137943013294113': {},
'175137943013294114': {'area_nm2': 253952,
'chunk_intersect_count': [[0, 0, 0], [0, 0, 0]],
'max_dt_nm': 62,
'mean_dt_nm': 25.390625,
'pca': [[-0.18603515625, 0.7392578125, -0.6474609375],
[-0.2296142578125, -0.67333984375, -0.70263671875],
[0.95556640625, -0.0178680419921875, -0.294921875]],
'rep_coord_nm': [535088, 248800, 164880],
'size_nm3': 4239360},
'175137943013294118': {'area_nm2': 2432,
'chunk_intersect_count': [[0, 0, 0], [0, 0, 0]],
'max_dt_nm': 16, …
```

Added L2Cache interface

---

caveclient/annotationengine.py
caveclient/base.py
caveclient/chunkedgraph.py
caveclient/jsonservice.py
caveclient/l2cache.py
caveclient/materializationengine.py

Various clients all have to have numpy encoders for the json dumps, however they all seem to be copy/paste. This adds a generic one to .base and uses it for the l2client.
Is there any reason to not move all of the other encoders to the same common one? I don't see any custom logic in any of them right now.

L2 cache JSON encoder

---

caveclient/annotationengine.py
caveclient/base.py
caveclient/chunkedgraph.py
caveclient/emannotationschemas.py
caveclient/frameworkclient.py
caveclient/infoservice.py
caveclient/jsonservice.py
caveclient/l2cache.py
caveclient/materializationengine.py
caveclient/session_config.py
requirements.txt
tests/test_chunkedgraph.py

Adding session options to the client:
* max retries (set to a default of 2)
* pool_maxsize — max number of threads that requests will keep around
* pool_block — If true, requests will not create more than the max number of threads.

Session options

---

caveclient/chunkedgraph.py

Bug: Timestamps from the PCG are converted to a datetime without timezone information and then simply tagged as UTC. This way, the datetime conversion depended on ones location.

Fixed timestamp conversion in get_root_timestamps

---

caveclient/annotationengine.py

Updates reference_table arguments in the create_table method with an addtional optional boolean which adds a database trigger function that updates the foreign key to the annotation table if the underlying annotation get updated.
In addition I updated some of the docstrings in the annotationengine.py file to be more accurate.

Extend reference annotation params 

---

caveclient/materializationengine.py
tests/test_materialization.py

This PR makes two additions to the materialization client:
1) Query and table metadata is optionally attached to a query dataframe using the `df.attrs` dictionary that pandas suggests. By default, metadata is attached. This includes all table metadata, as well as any query filters, and the materialization version or live query timestamp.
2) Added a `timestamp="now"` to the convert_timestamp parser, so that live query can be used without as much datetime  boilerplate. The metadata makes this more meaning, because the actual value of the live query timestamp is included and can be trivially passed to subsequent calls.

Dataframe attributes

---

caveclient/infoservice.py

While cloudvolume should not be a requirement, making a cloudvolume instance from a client is a frequent task with a good bit of boilerplate and some options that always require explaining to new users. This aims to add a convenience function in the client that provides sensible defaults.

Create cloud volume

---

caveclient/chunkedgraph.py
caveclient/materializationengine.py
tests/test_chunkedgraph.py
tests/test_materialization.py

adds a flag to allow automatic merging of reference annotations.
Choices made.. automatically add a "ref" suffix to the reference table columns that overlap (this will make the reference table id "id_ref" in the dataframe). 
Make this default True: This means metadata needs to be queried for every table even if not a reference, but i've enabled caching of this information now so it should be a one time cost per session-table. 
Haven't addressed join query as it would be more complicated.

Reference merge

---

caveclient/frameworkclient.py
caveclient/infoservice.py
caveclient/tools/caching.py
requirements.txt

Small fix to allow info_cache to be passed to the caveclient.
The idea here is that if one is working in a programmatic situation where many cave clients are being initialized all the time, the info cache could itself be cached (e.g. an LRU cache hashed by data stack and server name with an expiration time of an hour), avoiding an extra lookup roundtrip and an extra hit on the info service to get the same dict upon each caveclient initialization.

Set info cache from dict

---

caveclient/chunkedgraph.py
caveclient/endpoints.py

The addressed endpoint uses `admin_view` permissions. We are planning to change that to group-based permissions; but for the time being this function will only be useful for users with admin permissions on any dataset or higher.

Added user operation interface

---

caveclient/auth.py
caveclient/endpoints.py
caveclient/materializationengine.py

I'm trying to make it easier/more intuitive for users to setup tokens and support multiple databases.  This adds a new method for setting up a token which doesn't create a new one by default, and saves a token specific to the server by default, so now users will save and load those files as they interact with multiple servers and they can utilize the setup function either way.

adding methods to aid in token setup

---

caveclient/materializationengine.py

If a timestamp in live query exactly matches an existing version, do a regular versioned query_table.

live query uses query table for exact timestamp match

---

caveclient/datastack_lookup.py
caveclient/format_utils.py
caveclient/frameworkclient.py
caveclient/l2cache.py

Small quality of life feature: Store a map between datastack_name and the server_address in the ~/.cloudvolume directory. Accidentally built on top of the L2 warning removal, which is also a QoL issue and could be removed or just merged as one.

Datastack to server map

---

caveclient/materializationengine.py

When doing a live live query with annotation tables that have not yet been materialized, using getting metadata via the materialization client raises an error. This falls back to the annotation engine metadata in the case of an error.

Fall back to annotation table meta

---

caveclient/format_utils.py
caveclient/infoservice.py

This PR fixes the `format_for` argument to `client.info.segmentation_source` and `client.info.image_source` and adds a `cave_explorer` option that uses the more verbose `graphene://middleauth+https://` format

extend format_for to cave_explorer format

---

caveclient/chunkedgraph.py

Add a chunked graph function to get the best guess of an updated root id by overall in leaf chunks. Stop layer is set to (max_layers)-4 by default, which at least in the mm3 datasets seems to be a nice balance between resolution of chunks and speed. Optionally, multiple root ids and the fraction of overlap are possible to retrieve as well.
I would like to have a function so that people have an obvious next step when a query says "this id is not valid at this timestamp."

Suggest latest roots

---

tests/test_chunkedgraph.py

Fixes #120
(really the issue was fixed by https://github.com/seung-lab/PyChunkedGraph/pull/471 but this adds a test)

Add unit test for `is_valid_nodes`

---

caveclient/chunkedgraph.py
caveclient/materializationengine.py
docs/guide/materialization.rst
tests/test_chunkedgraph.py

This is necessary on v1 at least where timestamp filtering does not appear to give the result one would want.
```root_id = 720575940616772438
root_ts = client.chunkedgraph.get_root_timestamps(root_id)[0]
mat_timestamp=client.materialize.get_version_metadata(version=630)['time_stamp']
lineage_graph= client.chunkedgraph.get_lineage_graph(root_id, timestamp_past=root_ts,
timestamp_future=mat_timestamp)
print(f'root_ts: {root_ts} mat_timestamp: {mat_timestamp}')
for node in lineage_graph['nodes']:
node_ts= datetime.datetime.fromtimestamp(node['timestamp'])
node_ts=node_ts.astimezone(datetime.timezone.utc)
if ( (node_ts<mat_timestamp) or (node_ts>root_ts)):
print(node, node_ts)
```

fixes issues with lineage graph filtering with client side filtering

---

caveclient/chunkedgraph.py

- Added documentation for some returns which have a dictionary with many fields or dataframe etc.
- This was my main reason for this PR, as a new user I just found the meaning of many of these kinds of returns opaque.
-  This could probably still be improved. I took a stab at documenting these fields but if I could be wrong, feel free to add corrections. 
- Made everything use numpydoc, previously it was a mix 
- Used a more standard way of specifying types (see numpydoc) 
- Clarified references to actual variables in the docstrings with backticks 
- Added a few missing param descriptions 
- Tried to standardize nomenclature a bit, at least in this module
- asked for feedback on a couple

`chunkedgraph` module documentation improvements and standardization

---

caveclient/endpoints.py
caveclient/jsonservice.py

Various fixes for better handling neuroglancer states.
* Fix json encoding for state server upload to make integers encoded as strings, as neuroglancer expects.
* Add `version.json` endpoint for a neuroglancer URL to get build info.
* Add middleauth to state service URL endpoints for Cave Explorer deployments.
* Use neuroglancer version endpoint to guess target site deployment (to use `middleauth+` prefix or not) if not specified.

Fix ngl state encoding

---

caveclient/jsonservice.py

Two features for handling states.
1) Add a local save file. The main advantage here is just passing through the neuroglancer parser, but it also makes the state client a one-stop shop for handling state dictionaries.
2) Add a boolean `static_url` argument to `build_neuroglancer_url`. This will treat the first argument as a fully formed URL on its own, making it easy to build links to static sources through whatever formatting is needed.

add static url and local save

---

caveclient/materializationengine.py

Docs showed this parameter as `filter_spatial`, caused me some confusion (see https://github.com/seung-lab/CAVEclient/issues/137)

Fix wrong parameter name for `filter_spatial_dict` in `query_table`

---

caveclient/endpoints.py
caveclient/l2cache.py

Add the table_map endpoint to the l2cache client and a convenience function using it to see if your datastack has one.

add table map endpoint and l2 cache check

---

caveclient/materializationengine.py

It turns out there was an errant numpy array in df.attrs that was causing the problems with various pandas functions with __finalize__ (e.g. #155). Converting to lists fixes this.

BUG: no arrays in df.attrs

---

caveclient/emannotationschemas.py
caveclient/materializationengine.py
caveclient/tools/table_manager.py

client.materialize.tables.TABLE().query(timestamp=timestamp) was ignoring the timestamp value if the table was a reference table, since there is no timestamp parameter on join_query.

BUG: Use live live query for all join queries in tables

---

caveclient/base.py
caveclient/chunkedgraph.py
caveclient/endpoints.py
setup.py
tests/conftest.py
tests/test_chunkedgraph.py

Note: Currently, this is just for the chunkedgraph, but could easily be extended to the other services if we like the pattern
- Adds logic for talking to an endpoint which just returns the full semver for the service
- Happens on sub-client creation
- Stores this info as a `Version` object, which allows for easy operations like checking `>`,`>=` etc.
- Adds a decorator for convenience, which allows specification that a method or its keyword arguments are only valid for specific constraints of server version
- Opted not to do that for arguments, could discuss further but since those are required that felt like it didn't fit the pattern
- As an example, applies this decorator to a recent addition to the level2_chunk_graph `bounds` argument
A few things we discussed but I think are separate …

Add support for reasoning about server semantic version 

---

.bumpversion.cfg
caveclient/__init__.py
caveclient/base.py
caveclient/chunkedgraph.py
caveclient/endpoints.py
caveclient/jsonservice.py

Adds posting to new endpoints for segment properties json

Add segment props

---

caveclient/base.py
caveclient/chunkedgraph.py
tests/test_chunkedgraph.py

The new kwargs constraint throws an error if keyword cannot be used with the server version, but does not check if keyword is actually defined as anything. This checks if the kwarg is None before throwing the error to ignore null cases.
Closes #178 
- Clarifies that decorator should be used for keyword-only arguments
- Adds keyword only to level2_chunk_graph (technically a breaking change)

BUG: ignore kwarg=None in constrained calls

---

caveclient/base.py
caveclient/materializationengine.py

Before adding metadata attributes to the returned data frame, pass through JSON encode/decode to convert arrays, pandas series, etc into simple objects like lists. This will more robustly fix issues with df.attrs than before.

use JSONencoder to reformat metadata to simple objects

---

caveclient/materializationengine.py

Fixes a small bug in the get_tables_metadata function where the result was cached independent of version, causing incorrect results if tables were queried for two different versions. This fix adds a key for the cache that hashes on datastack name and version, which should uniquely define the result.

BUG: use a hashkey for correct version metadata cache

---

requirements.txt

python 3.12 installation fails with no c compiler setup because older versions of pyarrow are not available as pre-built wheels.

removing pyarrow pin

---

caveclient/auth.py
caveclient/datastack_lookup.py

Add datastack check to not record datastack-to-server mapping if datastack is None.

Require non-null datastack for using datastack to server address map

---

caveclient/base.py
caveclient/chunkedgraph.py

Adds two parameters to `chunkedgraph.get_root_timestamps`:
* `latest`: If True, gives the _latest_ timestamp for which the root id existed. If True, always returns a timestamp during which the root id exists.
* `timestamp`: Provides an explicit latest possible timestamp to use.
Note that the current server side implementation throws a 500 error is the timestamp is too early for the root id to exist yet.

Get root timestamps update

---

caveclient/chunkedgraph.py
caveclient/frameworkclient.py
caveclient/materializationengine.py
tests/test_chunkedgraph.py
tests/test_framework.py
tests/test_materialization.py

- Closes https://github.com/CAVEconnectome/CAVEclient/issues/191
- Closes https://github.com/CAVEconnectome/CAVEclient/issues/198
- Adds the ability to set a `version` during or after initialization for a CAVEclient
- This version also sets the corresponding `timestamp` for that version
- Currently only lets you set `version` directly, `timestamp` can't be set on its own
- This is up for debate - but I found it clunky to deal with either or both, there are many functions in materialization that only expect a version (so the behavior feels slightly unclear to me if only a timestamp is set), and I feel setting the version covers 99% of use cases anyway. 
- Changes logic for `MaterializationClient` and `ChunkedGraphClient` to defer to the `version`/`timestamp` if it is set at the …

Add versioning at the CAVEclient level

---

caveclient/materializationengine.py
docs/changelog.md

Add `log_warning` for `query_table`-like methods

---

caveclient/chunkedgraph.py

Sort of a hack/patch — get_roots_timestamp with latest=True gives a timestamp that has inconsistent behavior between timestamp-based queries and get_roots lookups. This patch subtracts 1 millisecond from the value in that particular case.

subtract millisecond for get_root_timestamps latest

---

caveclient/base.py
caveclient/chunkedgraph.py

Tweak version constraint to limit on minor versions within the major-version

fix version constraints for get root timestamps

---

caveclient/materializationengine.py

Due to the details of how the version checking decorator works, passing in (even empty) dictionaries to the new inequality filters would throw an error if running older versions of the materialization engine

Fix possible issue with `synapse_query` backwards compatibility

---

caveclient/annotationengine.py
caveclient/base.py
caveclient/chunkedgraph.py
caveclient/emannotationschemas.py
caveclient/frameworkclient.py
caveclient/infoservice.py
caveclient/jsonservice.py
caveclient/l2cache.py
caveclient/materializationengine.py
tests/test_materialization.py

Remove factory syntax for subclients

---

caveclient/tools/table_manager.py
docs/tutorials/materialization.md
tests/test_materialization.py

This will fix the overwriting of the `.query` interface to actually use the filters

Fix table interface + add test

---

caveclient/l2cache.py

- adds a method which returns a dataframe instead of a dict
- option to split columns, true by default but up for debate
- also fixed up the docs a bit

Add a `get_l2data_table` method to level2 cache

---

caveclient/auth.py
caveclient/frameworkclient.py
caveclient/l2cache.py
caveclient/tools/testing.py
docs/api/testing.md
docs/tutorials/advanced.md
mkdocs.yml
tests/conftest.py
tests/test_annotation.py
tests/test_chunkedgraph.py
tests/test_framework.py
tests/test_infoservice.py
tests/test_materialization.py

Adding a small submodule `caveclient.tools.testing` that makes it much easier to mock CAVEclients for testing.
1) CAVEclientMock lets you specify which services you anticipate loading, can take a datastack or use a only global-only version, can select what versions of each service you want to test against, specify api version availability, set materialization versions, etc. In general, CAVEclient initialization options are mocked out.
2) CAVEclient conftest.py was altered to use this tooling and several small tests were added to use these features.
3) This caught one or two bugs/issues thanks to these new tests.

Mock CAVEclient for testing

---

caveclient/jsonservice.py
tests/test_jsonclient.py

* `client.state.get_state_json` can now accept a url string directly, which bypasses the endpoints.
* `spelunker` is a valid name for google-style neuroglancer.
* Added basic tests for jsonstate getting state json
* Type hinting for state client functions

Allow get_state_json to accept direct URLs

---

caveclient/jsonservice.py

fixes a warning I keep getting in Python 3.12 upon import
`SyntaxWarning: invalid escape sequence '\/'`
`response_re = re.search(".*\/(\d+)", str(response.content))`

Add raw string notation

---

README.md
docs/contributing.md
uv.lock

Closes https://github.com/CAVEconnectome/CAVEclient/issues/279

Update contributing guidelines

---

caveclient/tools/table_manager.py
tests/test_materialization.py

Very small feature addition:
`client.materialize.tables` and `client.materialize.views` get a new function `find` that lets you search for a string in the list of table names. Very simple, no fuzzy 
So for example, `client.materialize.tables.find("syn")` would give a list of any tables that have `syn` in their name.

add tables.find and views.find

---

caveclient/tools/table_manager.py

Adding random_sample throughout table manager query argument.

add random sample to table manager

---

caveclient/base.py
caveclient/endpoints.py
caveclient/format_utils.py
caveclient/infoservice.py
caveclient/tools/testing.py
tests/conftest.py
tests/test_framework.py
tests/test_infoservice.py
tests/test_skeletons.py

Following recent changes to the info service, I'm adding `image_mirror` as an optional parameter on a number of info service calls. This will allow different sources of imagery to be incorporated naturally in the info service.
* New functions `get_image_mirrors` and `get_image_mirror_names` that show the full info or just the unique name of each mirror for an aligned volume.
* New parameters `image_mirror` in `get_aligned_volume_info`, `get_datastack_info`, `image_cloudvolume`, and `image_source` to select the correct source.
* Adding the new version endpoint to the info service to use these
* Fixed a bug across all clients where `self.default_endpoint_mapping` was changing if any of its keys were changed on the fly in a function. Most importantly, if you specified a different datastack …

Add imagery mirrors to the info file

---

caveclient/__main__.py
caveclient/auth.py
caveclient/datastack_lookup.py
caveclient/endpoints.py
caveclient/frameworkclient.py
caveclient/jsonservice.py
caveclient/tools/testing.py
pyproject.toml

Adding an onboarding method to CAVEclient and via a CLI.
```python
from caveclient import CAVEclient
CAVEclient.setup_token(server_address="https://global.daf-apis.com/") # No default here currently
```
or from a command line:
```bash
caveclient setup-token https://global.daf-apis.com
```
Will walk the user through getting a token from `https://global.daf-apis.com/sticky_auth/settings/tokens` (or equivalent, opens in a web browser by default), pasting it in (which will save it), and optionally (but recommended) setting up the datastack-to-server map for all data stacks that they see. An example is shown below:

Onboarding function
